Repository FidelCly/api, pull requests merged in 2023-07, with the labels that each got.

#1241 fix: set marketing mail nullable
  src/shop/shop.entity.ts
Labels: bug

#1115 feat: implement analytics
  .env.dev
  README.md
  package-lock.json
  package.json
  src/analytics/analytics.controller.ts
  src/analytics/analytics.dto.ts
  src/analytics/analytics.module.ts
  src/analytics/analytics.service.ts
  src/analytics/balance.pb.ts
  src/analytics/card.pb.ts
  src/analytics/general.pb.ts
  src/analytics/promotion.pb.ts
  src/analytics/shop.pb.ts
  src/app.module.ts
  src/balance/balance.controller.ts
  src/balance/balance.module.ts
  src/balance/balance.service.ts
  src/card/card.controller.ts
  src/card/card.entity.ts
  src/card/card.module.ts
  src/card/card.service.ts
  src/exception.interceptor.ts
  src/promotion/promotion.controller.ts
  src/promotion/promotion.module.ts
  src/promotion/promotion.service.ts
  src/shop/shop.controller.ts
  src/shop/shop.module.ts
  src/shop/shop.service.ts
  test/analytics/analytics.e2e-spec.ts
Labels: enhancement

#1284 fix: add condition on fider ability
  src/auth/ability.factory.ts
  src/auth/auth.guard.ts
Labels: bug

#1285 fix: checkout endpoint
  README.md
  package-lock.json
  src/analytics/card.pb.ts
  src/app.controller.ts
  src/app.dto.ts
  src/app.module.ts
  src/balance/balance.controller.ts
  src/balance/balance.service.ts
  src/card/card.dto.ts
  src/card/card.entity.ts
  src/card/card.service.ts
  test/app.e2e-spec.ts
  test/app.seed.ts
  test/balance/balance.e2e-spec.ts
  test/card/card.seed.ts
Labels: documentation, enhancement
